image: tmy2017/gitpod-workspace-full-vnc-php56
tasks:
  - init: |
      docker pull mysql:5.7
      # must "no interaction" so that symfony stuff like parameter.yml will not disrupt prebuild process
      composer install -n
      # strange error "Unable to write in the cache directory (/workspace/symfony2-behat-example/app/cache/dev)"
      sudo chmod -R 777 app/cache/dev
      docker run -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=symfony --name mysql_from_init -d mysql:5.7
      sudo php app/console doctrine:schema:create
      sudo yes|php app/console doctrine:fixtures:load
  - command: |
      docker start mysql_from_init
      app/console server:run

jetbrains:
  phpstorm:
    plugins:
      - com.intellij.lang.jsgraphql
      - org.sonarlint.idea
      # everything git related MUST be on backend
      - com.github.lppedd.idea-conventional-commit
      # as of (17-Jun-2023T11-51+0200) - inline blame is not working
      - zielu.gittoolbox

github:
  prebuilds:
    branches: true