image:
  file: .gitpod.Dockerfile
#tasks:
#  - init: |
#      docker pull mysql:5.7
#      sudo apt-get update
#      sudo add-apt-repository ppa:ondrej/php -y
#      sudo apt-get install php5.6-mysql php5.6-curl php5.6-intl -y
#      # must downgrade composer
#      composer self-update --2.2
#      sudo update-alternatives --set php /usr/bin/php5.6
#      composer install
#      php app/console doctrine:schema:create
#      yes|php app/console doctrine:fixtures:load
#
#  - before: |
#      # runs for every terminal, not just one, so makes sense to be here
#      sudo update-alternatives --set php /usr/bin/php5.6
#  - command: |
#      docker run -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=symfony -d mysql:5.7
#      app/console server:run

jetbrains:
  phpstorm:
    plugins:
      - com.intellij.lang.jsgraphql
      - org.sonarlint.idea
      # everything git related MUST be on backend
      - com.github.lppedd.idea-conventional-commit
      # as of (17-Jun-2023T11-51+0200) - inline blame is not working
      - zielu.gittoolbox

github:
  prebuilds:
    branches: true