image: tmy2017/gitpod-workspace-full-vnc-php56
tasks:
  - init: |
      docker pull mysql:5.7
      # must "no interaction" so that symfony stuff like parameter.yml will not disrupt prebuild process
      composer install -n
      # strange error "Unable to write in the cache directory (/workspace/symfony2-behat-example/app/cache/dev)"
      sudo chmod -R 777 app/cache/dev
  - command: |
      docker run -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=symfony -d mysql:5.7
      sleep 6 # seems mysql server starts slow, to avoid "mysql server has gone away error for commands below"
      php app/console doctrine:schema:create
      yes|php app/console doctrine:fixtures:load
      app/console server:run

jetbrains:
  phpstorm:
    plugins:
      - com.intellij.lang.jsgraphql
      - org.sonarlint.idea
      # everything git related MUST be on backend
      - com.github.lppedd.idea-conventional-commit
      # as of (17-Jun-2023T11-51+0200) - inline blame is not working
      - zielu.gittoolbox
      # must install at backend (30-Jun-2023T07-14+0200) and it works
      - com.sourcegraph.jetbrains

github:
  prebuilds:
    branches: true